# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Maws < Formula
  desc "Automatically apply extra cli flags from environment variables"
  homepage "https://github.com/favadi/xenvflags"
  version "0.0.1"
  license "BSD-2-Clause"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/favadi/xenvflags/releases/download/v0.0.1/xenvflags_0.0.1_Darwin_arm64.tar.gz"
      sha256 "f1162014b0877e673f0592d25e039577d8e453a4dd828dae0c5bf6157a8c50c2"

      def install
        bin.install "xenvflags"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/favadi/xenvflags/releases/download/v0.0.1/xenvflags_0.0.1_Darwin_x86_64.tar.gz"
      sha256 "4a0f45fc9ba60ad56232a6e96ae5b0caffb2c3f50327a7e9f98b44eb7717cf22"

      def install
        bin.install "xenvflags"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/favadi/xenvflags/releases/download/v0.0.1/xenvflags_0.0.1_Linux_arm64.tar.gz"
      sha256 "defd69c6ddd33378dc79775ada47a9a80ca72e5874e7c1702e3ace95dd943366"

      def install
        bin.install "xenvflags"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/favadi/xenvflags/releases/download/v0.0.1/xenvflags_0.0.1_Linux_x86_64.tar.gz"
      sha256 "27dcc7cc10a0f0e59cb1c3130f6f83c857bc3cf99b36a6991b57efa6098f6859"

      def install
        bin.install "xenvflags"
      end
    end
  end
end
